---
- name: Create and configure matterhorn and avalon users
  include_tasks: users.yml

- name: Create necessary directories
  include_tasks: setup_dirs.yml
 
- name: Install dependency packages
  include_tasks: install.yml

- name: Deploy avalon code
  include_tasks: avalon_deploy_codebase.yml

- name: Install gems
  include_tasks: avalon_bundle_install.yml