---
- name: Create avalon home directory
  file: 
    path: "{{ avalon_user.user_homedir }}"
    owner: "{{ avalon_user.user_name }}"
    group: "{{ avalon_user.user_name }}"
    mode: 0755
    state: directory

- name: Create documentroot directory
  file:
    path: "{{ doc_root }}"
    owner: "{{ avalon_user.user_name }}"
    group: "{{ avalon_user.user_name }}"
    mode: 0755
    state: directory

- name: Create httpd ssl directory
  file:
    path: "{{ ssl_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory